ASSESS_RISK_NODE = "ASSESS_RISK_NODE"
ASK_RISK_QUESTIONS_NODE = "ASK_RISK_QUESTIONS_NODE"
GET_RISK_ANSWERS_NODE = "GET_RISK_ANSWERS_NODE"
ASK_CONTINUE_WITH_PLAN_NODE = "CONTINUE_WITH_PLAN_NODE"
GET_CONTINUE_WITH_PLAN_NODE = "GET_CONTINUE_WITH_PLAN_NODE"

ASSESS_DEFENCE_NODE = "ASSESS_DEFENCE_NODE"
ASK_DEFENCE_QUESTIONS_NODE = "ASK_DEFENCE_QUESTIONS_NODE"
GET_DEFENCE_ANSWERS_NODE = "GET_DEFENCE_ANSWERS_NODE"
ASK_STRATEGY_NODE = "ASK_STRATEGY_NODE"
GET_STRATEGY_NODE = "GET_STRATEGY_NODE"

CREATE_LEAVE_PLAN_NODE = "CREATE_LEAVE_PLAN_NODE"
ASK_LEAVE_PLAN_QUESTIONS_NODE = "ASK_LEAVE_PLAN_QUESTIONS_NODE"
GET_LEAVE_PLAN_ANSWERS_NODE = "GET_LEAVE_PLAN_ANSWERS_NODE"

CREATE_STAY_PLAN_NODE = "CREATE_STAY_PLAN_NODE"
ASK_STAY_PLAN_QUESTIONS_NODE = "ASK_STAY_PLAN_QUESTIONS_NODE"
GET_STAY_PLAN_ANSWERS_NODE = "GET_STAY_PLAN_ANSWERS_NODE"

SHOW_PLAN_NODE = "SHOW_PLAN_NODE"
END_CONVERSATION_NODE = "END_CONVERSATION_NODE"
